- AWS
- AWS Lambda
- Adobe Creative Cloud
- Adobe Creative Suite
- Adobe Illustrator
- Airflow
- Alteryx
- Amazon S3
- Amazon Web Services (AWS)
- Android
- Angular
- Ansible
- Apache Airflow
- Apache Kafka
- Apache Spark
- Avro
- Azure
- Bash
- Bloomberg
- Bloomberg AIM
- Bloomberg APIs
- Bloomberg Terminal
- Canva
- Cassandra
- ChatGPT
- Chef
- Cisco
- CloudFormation
- Databricks
- Docker
- DocuSign
- ElasticSearch
- Excel
- Excel Macros
- FastAPI
- Figma
- Flink
- Gemini
- Git
- GitHub
- Google Analytics
- Google Cloud Platform (GCP)
- Grafana
- GraphQL
- Hadoop
- IBM MQ
- Informatica
- Instagram
- JIRA
- Java
- JavaScript
- Jenkins
- Jupyter Notebooks
- Kafka
- Kotlin
- Kubernetes
- LinkedIn
- Linux
- MS Excel
- Microsoft Access
- Microsoft Azure
- Microsoft Excel
- Microsoft Intune
- Microsoft PowerPoint
- Microsoft SQL Server
- Microsoft Visio
- Microsoft Word
- MuleSoft
- MySQL
- NONE
- Node.js
- NodeJS
- NumPy
- Office 365
- Oracle
- Pandas
- Parquet
- PeopleSoft
- Photoshop
- PostgreSQL
- Power BI
- PowerBI
- PowerPoint
- PowerShell
- Prometheus
- PyTorch
- Pyspark
- Python
- Qlik Sense
- RabbitMQ
- React
- React Native
- Redis
- Redux
- SAP
- SQL Server
- Salesforce
- Slack
- Snowflake
- Spark
- Splunk
- Spring
- SpringBoot
- TIBCO
- Tableau
- Terraform
- TypeScript
- UNIX
- VBA
- VMWARE
- Visio
- Vue.JS
- WebFlux
- Workday
- XML
- YouTube
- Zoom
