- Amazon Api Gateway
- Amazon Dynamodb
- Amazon Ecs
- Amazon Sagemaker
- Amplitude
- Apache Airflow
- Asana
- Aws
- Aws Fargate
- Aws Lambda
- Aws Step Functions
- Azure
- Canva
- Docker
- Dynamodb
- Elasticsearch
- Excel
- Facebook
- Figma
- Git
- Google
- Google Analytics
- Google Cloud Platform
- Instagram
- Java
- Javascript
- Jenkins
- Jira
- Kafka
- Kanban
- Kotlin
- Linkedin
- Microsoft Azure
- Microsoft Excel
- Microsoft Powerpoint
- Microsoft Sql Server
- Mysql
- NONE
- Pandas
- Postgresql
- Python
- React
- React Native
- Redux
- Salesforce
- Slack
- Snowflake
- Tableau
- Terraform
- Zoominfo
